# action.yml
name: 'Veracode Software Composition Analysis'
description: 'An action to execute Veracode Agent-Based SCA and import findings as issues'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  github_token:
    description: "Authorization token to query and create issues"
    required: true
  quick:
    description: ""
    required: false
    default: "false"
  update_advisor:
    description: "Show update advisor"
    required: false
    default: "false"
  min-cvss-for-issue:
    description: "The minimum CVSS value for vulnerability to be added as an issue"
    required: false
    default: "0"
  url:
    description: "A git URL to work with in case the scan is not for the current repository"
    required: false
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'