on: 
  push:
    paths-ignore:
      - "README.md"
      - "**.json"
      - "action.yml"
  schedule:
    - cron: 15 14 * * 6
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Test repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          quick: true
          #url: "https://github.com/Lerer/veracode-pipeline-scan-results-to-sarif"
          create-issues: true 
          fail-on-cvss: 1

        
